### ISSUE TITLE
Unable to Change Radio Button Color

### ISSUE THREAD

**Issue by dDevAhmed** [dDevAhmed/frontend_development_html_course#1]
I'm experiencing an issue with styling radio buttons in my form. ![Kaduna Electric Assignment](https://github.com/dDevAhmed/frontend_development_html_course/blob/master/assignment_2.html)

Despite multiple attempts to change both the default and active state colors, the radio buttons remain unaffected by the CSS styling. I've tried various approaches, including changing the background color, and border color, and using different CSS properties, but nothing seems to work. Here are the specific steps I took:

1. Changed the default color using:
```css
input[type=radio] {
    background-color: purple;
}
```
2. Attempted to style the active state:
```css
input[type=radio]:checked {
    background-color: purple;
    color: purple;
    border: 1px solid purple;
}
```

**Expected Behavior:**
The radio buttons should reflect the applied CSS styling changes for both the default and active states.

**Actual Behavior:**
The radio buttons remain unchanged, ignoring the applied CSS styles.

**Additional Information:**
If there are any recommended approaches or if I am missing something in the styling process, any guidance would be greatly appreciated. Thank you!

**Comment by nafiuishaaq** [comment]
I think what you are missing is that you are changing the background color instead of the border color 

example:
input[type="radio"] {
border: 2px solid purple;
}

**Comment by dDevAhmed** [comment]
I found the solution to the issue of changing the radio button color. Using the accent-color CSS property resolved the problem. Here's the code that worked:

```css
input[type="radio"] {
    accent-color: purple;
}
```

Thanks to everyone who contributed suggestions!
Closing this issue now.
